//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: CustomHelpProviderTests.cs
// Generated: 2025-12-01T11:59:57.215768
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class CustomHelpProviderTests
{
[Fact]
public void LoadEmbeddedFont_WithExistingFontFile_ShouldReturnFigletFont()
{
    // Arrange
    var settings = new CommandAppSettings();
    var helpProvider = new CustomHelpProvider(settings);

    // Act
    var font = helpProvider.LoadEmbeddedFont("slant.flf");

    // Assert
    Assert.NotNull(font);
    Assert.IsType<FigletFont>(font);
    Assert.Equal("Slant", font.Name);

[Fact]
public void Constructor_WithNullSettings_ThrowsArgumentNullException()
{
    // Arrange
    ICommandAppSettings nullSettings = null;

    // Act & Assert
    Assert.Throws<ArgumentNullException>(() => new CustomHelpProvider(nullSettings));
}
