//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: DelayProviderStubTests.cs
// Generated: 2025-12-01T18:59:20.117894
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class DelayProviderStubTests
{
[Fact]
public async Task DelayAsync_WithNegativeMilliseconds_ShouldRecordNegativeDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    int negativeDelay = -100;

    // Act
    await delayProvider.DelayAsync(negativeDelay);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(negativeDelay, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_WithVeryLargeMilliseconds_RecordsRequestedDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var veryLargeDelay = int.MaxValue;

    // Act
    await delayProvider.DelayAsync(veryLargeDelay);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(veryLargeDelay, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public void DelayAsync_CalledMultipleTimes_RecordsAllRequestedDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var expectedDelays = new[] { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        delayProvider.DelayAsync(delay).Wait();

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);
    
    // Verify Reset clears the recorded delays
    delayProvider.Reset();
    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_ConcurrentCalls_RecordsAllDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var tasks = new List<Task>();
    var expectedDelays = new[] { 100, 200, 300, 400, 500 };

    // Act
    foreach (var delay in expectedDelays)
    {
        tasks.Add(delayProvider.DelayAsync(delay));

    await Task.WhenAll(tasks);

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);
}
