//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: FileConsoleTests.cs
// Generated: 2025-11-27T14:24:43.543784
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;
using Xunit;



# Import: FileConsole

using System;
using System.IO;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Constructor_WithValidPathAndCreateMode_CreatesFileConsole()
    {
        // Arrange
        string testFilePath = Path.GetTempFileName();
        FileMode testFileMode = FileMode.Create;

        // Act
        using (var fileConsole = new FileConsole(testFilePath, testFileMode))
        {
            // Assert
            Assert.NotNull(fileConsole);
        }

        // Clean up
        File.Delete(testFilePath);

        // Additional assertion to verify file creation
        Assert.False(File.Exists(testFilePath), "The file should be deleted after FileConsole is disposed.");
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Constructor_WithValidPathAndAppendMode_CreatesFileConsole()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();

        try
        {
            // Act
            using (var fileConsole = new FileConsole(tempFilePath, FileMode.Append))
            {
                // Assert
                Assert.NotNull(fileConsole);
            }

            // Additional verification
            Assert.True(File.Exists(tempFilePath), $"File should exist at {tempFilePath}");
        }
        finally
        {
            // Clean up
            if (File.Exists(tempFilePath))
            {
                File.Delete(tempFilePath);
            }
        }
    }
}

# Import: FileConsole

using System;
using Xunit;

public class FileConsoleTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void Constructor_ThrowsArgumentException_WhenFilePathIsNullOrWhiteSpace(string invalidFilePath)
    {
        // Arrange
        Action act = () => new FileConsole(invalidFilePath, FileMode.Create);

        // Act & Assert
        var exception = Assert.Throws<ArgumentException>(act);
        Assert.Equal("File path cannot be null or empty", exception.Message);
        Assert.Equal("filePath", exception.ParamName);
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Dispose_ClosesFileWriter()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();
        var fileConsole = new FileConsole(tempFilePath, FileMode.Create);

        // Act
        fileConsole.Dispose();

        // Assert
        Assert.Throws<ObjectDisposedException>(() => 
        {
            using (var fs = new FileStream(tempFilePath, FileMode.Append))
            {
                // This should throw an ObjectDisposedException if the file is properly closed
            }
        });

        // Clean up
        File.Delete(tempFilePath);
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;
using Spectre.Console;

public class FileConsoleTests
{
    [Fact]
    public void Write_WritesRenderedContentToFile()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();
        var text = new Text("Hello, World!");

        // Act
        using (var fileConsole = new FileConsole(tempFilePath, FileMode.Create))
        {
            fileConsole.Write(text);
        }

        // Assert
        string fileContent = File.ReadAllText(tempFilePath);
        Assert.Equal("Hello, World!", fileContent);
        
        // Clean up
        File.Delete(tempFilePath);
    }
}

# Import: FileConsole

using System;
using System.IO;
using System.Text;
using Xunit;
using Spectre.Console.Rendering;

public class FileConsoleEncodingTests : IDisposable
{
    private readonly string _testFilePath = Path.GetTempFileName();

    [Fact]
    public void Write_HandlesNonAsciiCharacters_WritesCorrectlyToFile()
    {
        // Arrange
        using var fileConsole = new FileConsole(_testFilePath, FileMode.Create);
        var nonAsciiText = "こんにちは世界 - Hello World - 🌍";
        var renderable = new TestRenderable(nonAsciiText);

        // Act
        fileConsole.Write(renderable);
        fileConsole.Dispose(); // Ensure the file is flushed and closed

        // Assert
        string fileContent = File.ReadAllText(_testFilePath, Encoding.UTF8);
        Assert.Equal(nonAsciiText, fileContent, "The non-ASCII text should be correctly written to the file");
    }

    public void Dispose()
    {
        File.Delete(_testFilePath);
    }

    private class TestRenderable : IRenderable
    {
        private readonly string _text;

        public TestRenderable(string text)
        {
            _text = text;
        }

        public IEnumerable<Segment> Render(RenderOptions options, int width)
        {
            yield return new Segment(_text);
        }
    }
}

# Import: FileConsole

using System;
using System.IO;
using System.Text;
using Xunit;
using Spectre.Console.Rendering;

public class FileConsolePerformanceTests
{
    [Fact]
    public void Write_LargeAmountOfData_CompletesInReasonableTime()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();
        using var fileConsole = new FileConsole(tempFilePath, FileMode.Create);
        
        const int largeDataSize = 1_000_000; // 1 million characters
        var largeData = new string('A', largeDataSize);
        var renderable = new TestRenderable(largeData);

        // Act
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();
        fileConsole.Write(renderable);
        stopwatch.Stop();

        // Assert
        Assert.True(stopwatch.ElapsedMilliseconds < 5000, 
            $"Writing {largeDataSize} characters took {stopwatch.ElapsedMilliseconds}ms, which exceeds the expected 5000ms limit");

        // Cleanup
        File.Delete(tempFilePath);
    }

    private class TestRenderable : IRenderable
    {
        private readonly string _content;

        public TestRenderable(string content)
        {
            _content = content;
        }

        public IEnumerable<Segment> Render(RenderOptions options, int width)
        {
            yield return new Segment(_content);
        }
    }
}