//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IClockTests.cs
// Generated: 2025-12-01T11:59:57.216292
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IClockTests
{
[Fact]
public void ClockStub_Now_ReturnsFixedDate()
{
    // Arrange
    IClock clockStub = new ClockStub();
    DateTime expectedDateTime = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    DateTime result = clockStub.Now;

    // Assert
    Assert.Equal(expectedDateTime, result);
    Assert.Equal(1980, result.Year);
    Assert.Equal(1, result.Month);
    Assert.Equal(1, result.Day);
    Assert.Equal(10, result.Hour);
    Assert.Equal(5, result.Minute);
    Assert.Equal(0, result.Second);

[Fact]
public void IncrementingClockStub_Now_StartsFromInitialDate()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedInitialDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var firstCall = clock.Now;

    // Assert
    Assert.Equal(expectedInitialDate, firstCall, "The first call to IncrementingClockStub.Now should return the initial date");

[Fact]
public void IncrementingClockStub_BehavesConsistentlyAroundTypicalDSTTransition()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var dstTransitionDate = new DateTime(1980, 3, 30, 1, 59, 55); // Typical DST start date/time

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var currentTime = clock.Now;
        Assert.Equal(dstTransitionDate.AddSeconds(i * 5), currentTime);
        Assert.Equal(TimeSpan.FromSeconds(5), currentTime - dstTransitionDate.AddSeconds((i - 1) * 5));

    // Verify behavior after typical DST transition point
    var postDSTTime = clock.Now;
    Assert.Equal(dstTransitionDate.AddSeconds(25), postDSTTime);
    Assert.Equal(TimeSpan.FromSeconds(5), postDSTTime - dstTransitionDate.AddSeconds(20));

[Fact]
public void IncrementingClockStub_ShouldHandleDateChange()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var initialDate = new DateTime(1980, 1, 1, 23, 59, 55); // 5 seconds before midnight
    
    // Act
    var firstCall = clock.Now;
    var secondCall = clock.Now;
    var thirdCall = clock.Now;

    // Assert
    Assert.Equal(initialDate, firstCall, "First call should return the initial date");
    Assert.Equal(new DateTime(1980, 1, 2, 0, 0, 0), secondCall, "Second call should be exactly at midnight");
    Assert.Equal(new DateTime(1980, 1, 2, 0, 0, 5), thirdCall, "Third call should be 5 seconds into the new day");

[Fact]
public void Now_ReturnsCurrentSystemTime()
{
    // Arrange
    var clock = new Clock();
    var beforeTest = DateTime.Now;

    // Act
    var result = clock.Now;

    // Assert
    var afterTest = DateTime.Now;
    Assert.InRange(result, beforeTest, afterTest);

[Fact]
public void IncrementingClockStub_Now_StartsFromExpectedDateTime()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var actualFirstDate = clock.Now;

    // Assert
    Assert.Equal(expectedStartDate, actualFirstDate, 
        "IncrementingClockStub.Now should start from 1980-01-01 10:05:00");

[Fact]
public void IncrementingClockStub_Now_IncrementsByFiveSecondsOnMultipleCalls()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var result = clock.Now;
        var expectedTime = expectedStartDate.AddSeconds(i * 5);
        
        Assert.Equal(expectedTime, result, 
            $"Call {i + 1}: Expected {expectedTime}, but got {result}");

[Fact]
public void ClockStub_Now_ReturnsFixedDateTime()
{
    // Arrange
    var clockStub = new ClockStub();
    var expectedDateTime = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var result = clockStub.Now;

    // Assert
    Assert.Equal(expectedDateTime, result);
    Assert.Equal(1980, result.Year);
    Assert.Equal(1, result.Month);
    Assert.Equal(1, result.Day);
    Assert.Equal(10, result.Hour);
    Assert.Equal(5, result.Minute);
    Assert.Equal(0, result.Second);

[Fact]
public void IncrementingClockStub_Now_StartsAtCorrectInitialTime()
{
    // Arrange
    var clockStub = new IncrementingClockStub();
    var expectedInitialTime = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var actualInitialTime = clockStub.Now;

    // Assert
    Assert.Equal(expectedInitialTime, actualInitialTime, 
        "IncrementingClockStub.Now should start at 1980-01-01 10:05:00");
}
