//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IClockTests.cs
// Generated: 2025-12-01T15:54:05.436592
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IClockTests
{
[Fact]
public void IncrementingClockStub_Now_IncrementsBy5SecondsOnEachCall()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var currentTime = clock.Now;
        var expectedTime = expectedStartDate.AddSeconds(i * 5);
        
        Assert.Equal(expectedTime, currentTime, 
            $"Call {i + 1}: Expected {expectedTime}, but got {currentTime}");

[Fact]
public void IncrementingClockStub_Now_StartsFromCorrectInitialDate()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedInitialDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var actualInitialDate = clock.Now;

    // Assert
    Assert.Equal(expectedInitialDate, actualInitialDate);
    Assert.Equal(0, (actualInitialDate - expectedInitialDate).TotalSeconds, 
        "The initial date should match exactly without any increments.");

[Fact]
public void AllClockImplementationsImplementIClock()
{
    // Arrange
    var clockTypes = new Type[] 
    { 
        typeof(Clock), 
        typeof(ClockStub), 
        typeof(IncrementingClockStub) 
    };

    // Act & Assert
    foreach (var clockType in clockTypes)
    {
        Assert.True(typeof(IClock).IsAssignableFrom(clockType), 
            $"{clockType.Name} should implement IClock interface");
        
        var instance = Activator.CreateInstance(clockType);
        Assert.NotNull(instance);
        Assert.IsAssignableFrom<IClock>(instance);
        
        var nowProperty = clockType.GetProperty("Now");
        Assert.NotNull(nowProperty);
        Assert.Equal(typeof(DateTime), nowProperty.PropertyType);

[Fact]
public void Clock_Now_ReturnsCurrentSystemTime()
{
    // Arrange
    var clock = new Clock();
    var beforeTest = DateTime.Now;

    // Act
    var result = clock.Now;
    var afterTest = DateTime.Now;

    // Assert
    Assert.True(result >= beforeTest && result <= afterTest, 
        $"Clock.Now returned {result}, which is not between {beforeTest} and {afterTest}");

[Fact]
public void IncrementingClockStub_Now_IncrementsByFiveSecondsOverMultipleCalls()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var currentTime = clock.Now;
        var expectedTime = expectedStartDate.AddSeconds(i * 5);

        Assert.Equal(expectedTime, currentTime, 
            $"Call {i + 1}: Expected {expectedTime}, but got {currentTime}");

[Fact]
public void Now_ReturnsIncrementedTimeOnEachCall()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 3; i++)
    {
        var result = clock.Now;
        var expectedTime = expectedStartDate.AddSeconds(i * 5);

        Assert.Equal(expectedTime, result, 
            $"Call {i + 1}: Expected {expectedTime}, but got {result}");
}
