//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IClockTests.cs
// Generated: 2025-12-01T18:59:20.119571
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IClockTests
{
[Fact]
public void Clock_Now_ReturnsCurrentSystemTime()
{
    // Arrange
    var clock = new Clock();
    var beforeTest = DateTime.Now;

    // Act
    var result = clock.Now;
    var afterTest = DateTime.Now;

    // Assert
    Assert.InRange(result, beforeTest, afterTest);
    Assert.Equal(DateTime.Now.Date, result.Date);
    Assert.Equal(DateTime.Now.TimeOfDay.Hours, result.TimeOfDay.Hours);
    Assert.Equal(DateTime.Now.TimeOfDay.Minutes, result.TimeOfDay.Minutes);
}
