//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IDelayProviderTests.cs
// Generated: 2025-12-01T18:59:20.117633
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IDelayProviderTests
{
[Fact]
public async Task DelayAsync_WithPositiveDelay_WaitsForSpecifiedTime()
{
    // Arrange
    var delayProvider = new DelayProvider();
    int delayMilliseconds = 100;
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(delayMilliseconds);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds >= delayMilliseconds, 
        $"Delay should be at least {delayMilliseconds}ms, but was {stopwatch.ElapsedMilliseconds}ms");

[Fact]
public async Task DelayAsync_WithZeroDelay_CompletesImmediately()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(0);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds < 10, $"Expected delay to complete immediately, but it took {stopwatch.ElapsedMilliseconds} ms");

[Fact]
public async Task DelayAsync_WithImmediatelyCanceledToken_ThrowsTaskCanceledException()
{
    // Arrange
    var delayProvider = new DelayProvider();
    using var cts = new CancellationTokenSource();
    cts.Cancel(); // Cancel the token immediately

    // Act & Assert
    await Assert.ThrowsAsync<TaskCanceledException>(() => 
        delayProvider.DelayAsync(1000, cts.Token)
    );

[Fact]
public async Task DelayAsync_CancelledDuringDelay_ThrowsOperationCanceledException()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var cts = new CancellationTokenSource();
    var delay = 1000; // 1 second delay

    // Act & Assert
    var delayTask = delayProvider.DelayAsync(delay, cts.Token);
    
    // Cancel the token after a short time (e.g., 100ms)
    await Task.Delay(100);
    cts.Cancel();

    // Assert that the task throws OperationCanceledException
    await Assert.ThrowsAsync<OperationCanceledException>(() => delayTask);

[Fact]
public async Task DelayAsync_WithZeroMilliseconds_ReturnsImmediately()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(0);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds < 10, $"Expected delay to return immediately, but it took {stopwatch.ElapsedMilliseconds} ms");

[Fact]
public async Task DelayAsync_WithVerySmallDelay_ShouldCompleteQuickly()
{
    // Arrange
    var delayProvider = new DelayProvider();
    int verySmallDelay = 1;
    var stopwatch = System.Diagnostics.Stopwatch.StartNew();

    // Act
    await delayProvider.DelayAsync(verySmallDelay);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds >= verySmallDelay, 
        $"The delay should be at least {verySmallDelay} milliseconds, but it was {stopwatch.ElapsedMilliseconds} milliseconds.");
    Assert.True(stopwatch.ElapsedMilliseconds < 100, 
        $"The delay should complete quickly, but it took {stopwatch.ElapsedMilliseconds} milliseconds.");
}
