//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-12-01T11:59:57.215089
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServerLatencyAsync_WithProgressUpdates_ShouldReportProgress()
{
    // Arrange
    var mockServer = new Mock<IServer>();
    var speedTestService = new Mock<ISpeedTestService>();
    var progressUpdates = new List<int>();
    
    speedTestService
        .Setup(s => s.GetServerLatencyAsync(
            It.IsAny<IServer>(),
            It.IsAny<Action<SpeedTestProgress>>(),
            It.IsAny<CancellationToken>()))
        .Callback<IServer, Action<SpeedTestProgress>, CancellationToken>((_, progress, _) =>
        {
            progress(new SpeedTestProgress { Percentage = 0 });
            progress(new SpeedTestProgress { Percentage = 50 });
            progress(new SpeedTestProgress { Percentage = 100 });
        })
        .ReturnsAsync(new ServerLatencyResult(mockServer.Object, 100));

    // Act
    var result = await speedTestService.Object.GetServerLatencyAsync(
        mockServer.Object,
        progress => progressUpdates.Add(progress.Percentage),
        CancellationToken.None);

    // Assert
    Assert.Equal(3, progressUpdates.Count);
    Assert.Equal(new[] { 0, 50, 100 }, progressUpdates);
    Assert.Equal(100, result.Latency);
    Assert.Same(mockServer.Object, result.Server);

[Fact]
public async Task GetServersAsync_ShouldRespectCancellationToken()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    var cts = new CancellationTokenSource();
    
    mockSpeedTestService
        .Setup(s => s.GetServersAsync(It.IsAny<CancellationToken>()))
        .Returns((CancellationToken ct) => Task.Delay(5000, ct).ContinueWith(_ => new IServer[0], ct));

    // Act
    cts.CancelAfter(100); // Cancel after 100ms
    
    // Assert
    await Assert.ThrowsAsync<TaskCanceledException>(async () =>
    {
        await mockSpeedTestService.Object.GetServersAsync(cts.Token);
    });
}
