//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-11-28T09:29:09.097861
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServersAsync_ReturnsLargeNumberOfServers()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    var largeServerList = Enumerable.Range(0, 10000).Select(i => Mock.Of<IServer>()).ToArray();
    mockSpeedTestService.Setup(s => s.GetServersAsync(It.IsAny<CancellationToken>()))
        .ReturnsAsync(largeServerList);

    // Act
    var result = await mockSpeedTestService.Object.GetServersAsync();

    // Assert
    Assert.NotNull(result);
    Assert.Equal(10000, result.Length);
    Assert.All(result, server => Assert.IsAssignableFrom<IServer>(server));

[Fact]
public async Task GetServerLatencyAsync_WithUnreachableServer_ThrowsException()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    var unreachableServer = new Mock<IServer>();
    unreachableServer.Setup(s => s.Url).Returns("https://unreachable-server.com");

    mockSpeedTestService
        .Setup(s => s.GetServerLatencyAsync(It.IsAny<IServer>(), It.IsAny<CancellationToken>()))
        .ThrowsAsync(new Exception("Unable to reach server"));

    // Act & Assert
    await Assert.ThrowsAsync<Exception>(() => 
        mockSpeedTestService.Object.GetServerLatencyAsync(unreachableServer.Object));
}
