//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-12-01T15:54:05.429750
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServersAsync_ReturnsEmptyArray_WhenNoServersAvailable()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    mockSpeedTestService.Setup(s => s.GetServersAsync(It.IsAny<CancellationToken>()))
        .ReturnsAsync(Array.Empty<IServer>());

    // Act
    var result = await mockSpeedTestService.Object.GetServersAsync();

    // Assert
    Assert.NotNull(result);
    Assert.Empty(result);
    Assert.IsType<IServer[]>(result);
}
