//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IWaiterTests.cs
// Generated: 2025-12-01T09:50:19.748032
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IWaiterTests
{
[Fact]
public async Task NoDelayStub_Delay_ShouldCompleteImmediatelyWithCancellation()
{
    // Arrange
    var noDelayStub = new NoDelayStub();
    var cts = new CancellationTokenSource();
    var delay = TimeSpan.FromSeconds(5);

    // Act
    var startTime = DateTime.UtcNow;
    await noDelayStub.Delay(delay, cts.Token);
    var endTime = DateTime.UtcNow;

    // Assert
    var elapsedTime = endTime - startTime;
    Assert.True(elapsedTime < TimeSpan.FromMilliseconds(100), $"NoDelayStub.Delay did not complete immediately. Elapsed time: {elapsedTime.TotalMilliseconds}ms");
    Assert.Equal(1, noDelayStub.CallCount);

[Fact]
public async Task Delay_ShouldThrowOperationCanceledException_WhenCancellationRequested()
{
    // Arrange
    var waiter = new Waiter();
    var cts = new CancellationTokenSource();
    var delay = TimeSpan.FromSeconds(5);

    // Act
    cts.Cancel(); // Cancel immediately
    var task = waiter.Delay(delay, cts.Token);

    // Assert
    await Assert.ThrowsAsync<OperationCanceledException>(() => task);
}
