//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IWaiterTests.cs
// Generated: 2025-12-01T15:54:05.440327
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IWaiterTests
{
[Theory]
[InlineData(0)]
[InlineData(1)]
[InlineData(100)]
[InlineData(1000)]
public async Task Delay_WithVariousTimeSpans_ShouldWaitForSpecifiedDuration(int milliseconds)
{
    // Arrange
    var waiter = new Waiter();
    var delay = TimeSpan.FromMilliseconds(milliseconds);
    var stopwatch = new System.Diagnostics.Stopwatch();
    var cancellationToken = CancellationToken.None;

    // Act
    stopwatch.Start();
    await waiter.Delay(delay, cancellationToken);
    stopwatch.Stop();

    // Assert
    var actualDelay = stopwatch.Elapsed;
    Assert.True(actualDelay >= delay, $"Expected delay of at least {delay}, but actual delay was {actualDelay}");
    Assert.True(actualDelay < delay.Add(TimeSpan.FromMilliseconds(100)), 
                $"Expected delay close to {delay}, but actual delay was {actualDelay}");

[Fact]
public async Task SelfCancellingWaiter_Delay_CancelsWhenMaxCallCountReached()
{
    // Arrange
    int maxCallCount = 3;
    using var cts = new CancellationTokenSource();
    var waiter = new SelfCancellingWaiter(maxCallCount, cts);

    // Act & Assert
    for (int i = 0; i < maxCallCount; i++)
    {
        await waiter.Delay(TimeSpan.FromMilliseconds(1), cts.Token);
        Assert.False(cts.IsCancellationRequested, $"Cancellation should not be requested at call {i + 1}");

    // The next call should trigger cancellation
    await waiter.Delay(TimeSpan.FromMilliseconds(1), cts.Token);
    
    Assert.True(cts.IsCancellationRequested, "Cancellation should be requested after exceeding maxCallCount");
    Assert.Equal(maxCallCount + 1, waiter.CallCount);
}
