//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IWaiterTests.cs
// Generated: 2025-12-01T11:59:57.217735
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IWaiterTests
{
[Theory]
[InlineData(0)]
[InlineData(1)]
[InlineData(100)]
[InlineData(1000)]
public async Task Delay_ShouldRespectProvidedTimeSpan(int milliseconds)
{
    // Arrange
    var waiter = new Waiter();
    var delay = TimeSpan.FromMilliseconds(milliseconds);
    var cts = new CancellationTokenSource();

    // Act
    var startTime = DateTime.UtcNow;
    await waiter.Delay(delay, cts.Token);
    var endTime = DateTime.UtcNow;

    // Assert
    var actualDelay = endTime - startTime;
    Assert.True(actualDelay >= delay, $"Actual delay ({actualDelay}) should be greater than or equal to requested delay ({delay})");
    Assert.True(actualDelay < delay.Add(TimeSpan.FromSeconds(1)), $"Actual delay ({actualDelay}) should be less than requested delay plus 1 second tolerance ({delay.Add(TimeSpan.FromSeconds(1))})");

[Fact]
public async Task Delay_WithCancellationTokenNone_CompletesWithoutCancellation()
{
    // Arrange
    IWaiter waiter = new Waiter();
    TimeSpan delay = TimeSpan.FromMilliseconds(50);
    
    // Act & Assert
    await Assert.DoesNotThrowAsync(async () =>
    {
        await waiter.Delay(delay, CancellationToken.None);
    });

[Theory]
[InlineData(0)]
[InlineData(100)]
[InlineData(1000)]
[InlineData(5000)]
public async Task Delay_WaitsForSpecifiedTime(int milliseconds)
{
    // Arrange
    var waiter = new Waiter();
    var delay = TimeSpan.FromMilliseconds(milliseconds);
    var cts = new CancellationTokenSource();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await waiter.Delay(delay, cts.Token);
    stopwatch.Stop();

    // Assert
    var actualDelay = stopwatch.Elapsed;
    Assert.True(actualDelay >= delay, $"Actual delay ({actualDelay}) should be greater than or equal to requested delay ({delay})");
    Assert.True(actualDelay < delay.Add(TimeSpan.FromSeconds(1)), $"Actual delay ({actualDelay}) should not exceed requested delay ({delay}) by more than 1 second");

[Fact]
public async Task Delay_WithCancellation_ShouldThrowOperationCanceledException()
{
    // Arrange
    var waiter = new Waiter();
    var cts = new CancellationTokenSource();
    var delay = TimeSpan.FromSeconds(5);

    // Act & Assert
    cts.Cancel(); // Cancel immediately
    await Assert.ThrowsAsync<OperationCanceledException>(() => 
        waiter.Delay(delay, cts.Token));
}
