//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ProgramTests.cs
// Generated: 2025-11-27T19:29:06.193041
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ProgramTests
{
[Fact]
public void GetCommandApp_ReturnsConfiguredCommandApp()
{
    // Arrange
    var mockRegistrar = new Mock<ITypeRegistrar>();

    // Act
    var app = Program.GetCommandApp(mockRegistrar.Object);

    // Assert
    Assert.NotNull(app);
    Assert.IsType<CommandApp<SpeedTestCommand>>(app);
    
    // Verify that the app is configured with the correct description
    var appType = app.GetType();
    var descriptionProperty = appType.GetProperty("Description", BindingFlags.NonPublic | BindingFlags.Instance);
    Assert.NotNull(descriptionProperty);
    var description = descriptionProperty.GetValue(app) as string;
    Assert.Equal(Program.Description, description);

[Fact]
public void Main_WithTestArgument_UsesStubImplementations()
{
    // Arrange
    string[] args = new[] { "--test" };

    // Act
    int result = Program.Main(args);

    // Assert
    Assert.Equal(0, result); // Assuming successful execution returns 0
    
    // Note: We cannot directly assert the use of stub implementations
    // as they are registered internally and not exposed.
    // A more comprehensive test would require refactoring to expose
    // the registrar or use a mocking framework.
    
    // This test primarily ensures that the Main method executes
    // without throwing an exception when the --test flag is provided.
}
