//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ProgramTests.cs
// Generated: 2025-11-27T19:39:18.451261
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ProgramTests
{
[Fact]
public void Main_WithTestArgument_RegistersStubImplementations()
{
    // Arrange
    string[] args = new[] { "--test" };

    // Act
    int result = Program.Main(args);

    // Assert
    Assert.Equal(0, result); // Assuming successful execution returns 0

    // Note: We can't directly access the registrar to verify registrations
    // due to it being a local variable in the Main method.
    // In a real-world scenario, we might need to refactor the code to make
    // the registrations testable, or use a mocking framework to intercept
    // the registrations.

    // The following assertions are comments because we can't actually test them
    // without modifying the original code or using advanced mocking techniques:

    // Assert.IsType<SpeedTestStub>(registrar.Resolve<ISpeedTestService>());
    // Assert.IsType<ClockStub>(registrar.Resolve<IClock>());
    // Assert.IsType<NoDelayStub>(registrar.Resolve<IWaiter>());

[Fact]
public void Main_WithEmptyArgumentArray_ReturnsNonZeroExitCode()
{
    // Arrange
    string[] emptyArgs = Array.Empty<string>();

    // Act
    int result = Program.Main(emptyArgs);

    // Assert
    Assert.NotEqual(0, result, "Main should return a non-zero exit code when given an empty argument array");
}
