//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: SpeedTestTests.cs
// Generated: 2025-12-02T14:17:43.357743
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class SpeedTestTests
{
[Fact]
public void CalculateSpeed_WithValidPositiveInputs_ReturnsCorrectSpeed()
{
    // Arrange
    var speedTestService = new SpeedTestService();
    double distance = 100.0; // 100 meters
    double time = 10.0; // 10 seconds

    // Act
    double speed = speedTestService.CalculateSpeed(distance, time);

    // Assert
    Assert.Equal(10.0, speed, 3); // Expected speed is 10 m/s, with a precision of 3 decimal places
    Assert.True(speed > 0, "Calculated speed should be positive");
}
