"""
TestWeaver Generated Tests

Auto-generated by DeeperCore TestWeaver
File: tests/test_TestWeaver_generated.py
Generated: 2025-11-27T11:01:22.406896

These tests cover edge cases and boundary conditions discovered
through TestWeaver's 5-phase analysis methodology.
"""

import pytest


# Import: FileConsole

using System;
using System.IO;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Constructor_WithValidPathAndCreateMode_CreatesFileConsole()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();

        try
        {
            // Act
            using (var fileConsole = new FileConsole(tempFilePath, FileMode.Create))
            {
                // Assert
                Assert.NotNull(fileConsole);
                Assert.True(File.Exists(tempFilePath), $"File should be created at {tempFilePath}");
            }

            // Additional check after disposal
            Assert.True(File.Exists(tempFilePath), $"File should still exist after disposal at {tempFilePath}");
        }
        finally
        {
            // Clean up
            if (File.Exists(tempFilePath))
            {
                File.Delete(tempFilePath);
            }
        }
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Constructor_ValidPathAndAppendMode_CreatesInstance()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();

        try
        {
            // Act
            using (var fileConsole = new FileConsole(tempFilePath, FileMode.Append))
            {
                // Assert
                Assert.NotNull(fileConsole);
            }

            // Additional check to ensure file exists
            Assert.True(File.Exists(tempFilePath), $"File should exist at {tempFilePath}");
        }
        finally
        {
            // Clean up
            if (File.Exists(tempFilePath))
            {
                File.Delete(tempFilePath);
            }
        }
    }
}

# Import: FileConsole

using System;
using Xunit;

public class FileConsoleTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("\t")]
    [InlineData("\n")]
    public void Constructor_WithNullOrEmptyFilePath_ThrowsArgumentException(string filePath)
    {
        // Arrange
        Action act = () => new FileConsole(filePath, FileMode.Create);

        // Act & Assert
        var exception = Assert.Throws<ArgumentException>(act);
        Assert.Equal("File path cannot be null or empty", exception.Message);
        Assert.Equal("filePath", exception.ParamName);
    }
}

# Import: FileConsole

using System;
using Xunit;

public class FileConsoleTests
{
    [Fact]
    public void Constructor_WithInvalidFilePath_ThrowsArgumentException()
    {
        // Arrange
        string invalidFilePath = "C:\\*<>?|:";

        // Act & Assert
        var exception = Assert.Throws<ArgumentException>(() => new FileConsole(invalidFilePath, FileMode.Create));
        
        Assert.Equal("File path cannot be null or empty", exception.Message);
        Assert.Equal("filePath", exception.ParamName);
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;
using Spectre.Console;
using Spectre.Console.Rendering;

public class FileConsoleTests
{
    [Fact]
    public void Write_WithVariousContentTypes_WritesCorrectlyToFile()
    {
        // Arrange
        string testFilePath = Path.GetTempFileName();
        using (var fileConsole = new FileConsole(testFilePath, FileMode.Create))
        {
            // Act
            fileConsole.Write(new Text("Plain text")); // Simple text
            fileConsole.Write(new Table().AddColumn("Column 1").AddRow("Table content")); // Table
            fileConsole.Write(new Markup("[bold]Marked up[/] text")); // Markup
            fileConsole.Write(new Text("")); // Empty string
            fileConsole.Write(new Text("   ")); // Whitespace only
            fileConsole.Write(new Text("Unicode: ♠♥♦♣")); // Unicode characters
            fileConsole.Write(new Text("Emoji: 😀🌈")); // Emoji
            fileConsole.Write(new Text("RTL: שלום")); // Right-to-left text
        }

        // Assert
        string fileContent = File.ReadAllText(testFilePath);
        Assert.Contains("Plain text", fileContent);
        Assert.Contains("Column 1", fileContent);
        Assert.Contains("Table content", fileContent);
        Assert.Contains("Marked up text", fileContent);
        Assert.Contains("Unicode: ♠♥♦♣", fileContent);
        Assert.Contains("Emoji: 😀🌈", fileContent);
        Assert.Contains("RTL: שלום", fileContent);
        Assert.Contains("   ", fileContent); // Whitespace preserved
        
        // Clean up
        File.Delete(testFilePath);
    }
}

# Import: FileConsole

using System;
using System.IO;
using Xunit;
using Spectre.Console;
using Spectre.Console.Rendering;

public class FileConsoleTests
{
    [Fact]
    public void Write_WithAnsiEscapeCodes_DoesNotWriteAnsiCodesToFile()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();
        try
        {
            using (var fileConsole = new FileConsole(tempFilePath, FileMode.Create))
            {
                var ansiText = new Markup("[bold red]Hello[/] [green]World[/]");

                // Act
                fileConsole.Write(ansiText);
            }

            // Assert
            string fileContent = File.ReadAllText(tempFilePath);
            Assert.Equal("Hello World", fileContent);
            Assert.DoesNotContain("[bold red]", fileContent);
            Assert.DoesNotContain("[/]", fileContent);
            Assert.DoesNotContain("[green]", fileContent);
        }
        finally
        {
            // Clean up
            File.Delete(tempFilePath);
        }
    }
}

# Import: FileConsoleOutput

using System;
using System.IO;
using Xunit;

public class FileConsoleOutputTests
{
    [Fact]
    public void Constructor_WithValidFilePathAndFileMode_CreatesInstance()
    {
        // Arrange
        string tempFilePath = Path.GetTempFileName();

        // Act
        FileConsoleOutput fileConsoleOutput = null;
        Exception exception = null;
        try
        {
            fileConsoleOutput = new FileConsoleOutput(new StreamWriter(tempFilePath, false));
        }
        catch (Exception ex)
        {
            exception = ex;
        }

        // Assert
        Assert.Null(exception);
        Assert.NotNull(fileConsoleOutput);

        // Clean up
        if (File.Exists(tempFilePath))
        {
            File.Delete(tempFilePath);
        }
    }
}