version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "FrankRay78"
    assignees:
      - "FrankRay78"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "chore"